---
name: Cloud Native Transformation Patterns
title: Cloud Native Transformation Patterns

kramdown: 
  parse_block_html: true
permalink: /:title

collections:
  development-design:
    output: true
  infrastructure-cloud:
    output: true
  organization-culture:
    output: true
  strategy-risk-reduction:
    output: true

# Google Analytics
google_analytics: UA-53586058-2
